repos:
  - repo: local
    hooks:
      - id: pre-commit-hooks
        name: Run all project hooks
        entry: python hooks/pre-commit.py
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]
